apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transaction-analyzer-vat
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Cloud Run resource limits
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Request timeout
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/transaction-analyzer-vat:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true